[package]
name = "audio_share"
version = "0.1.0"
edition = "2024"

[dependencies]
cpal = "0.16"
webrtc = "0.13"
anyhow = "1.0"
hound = "3.5"
tokio = { version = "1.45", features = ["full"] }
opus = "0.3.0"
